import type { Metadata } from "next";
import { Inter, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import NavigationBar from "@/components/layout/NavigationBar";
import MobileBottomNav from "@/components/layout/MobileBottomNav";

// 使用 Inter 字体 - 更圆润、友好的无衬线字体
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="zh-CN">
      <body
        className={`${inter.variable} ${geistMono.variable} antialiased`}
      >
        {/* 装饰性椭圆 */}
        <div className="decorative-circle-1" />
        <div className="decorative-circle-2" />
        <Providers>
          <NavigationBar />
          {children}
          <MobileBottomNav />
        </Providers>
      </body>
    </html>
  );
}
